### ISSUE TITLE
update display sequence for trial and practice view

### ISSUE THREAD

**Issue by michael-franke** [ProComPrag/QuantShapeCol-spr-001#3]
Currently, the lines for the words are visible already when the picture is still shown.
Now we also have a QUD (question on top of the picture).
Ideally, we'd like to have a display sequence like this:
- show QUD immediately
- show fixation cross for picture
- replace fixation cross with picture
- remove picture & show lines for SRP at the same time

**Comment by stelaseldano** [comment]
Currently the QUD and the fixation cross show at the same time, is that how it is supposed to be or there should be some time in between?

**Comment by michael-franke** [comment]
Could we have a one-second lag?
Thanks!!

**Comment by stelaseldano** [comment]
Sure! :)
